"""Turn policies/*.md into sql/03_policies.sql (one row per clause) plus a Cortex Search service."""
import glob
import os
import re

ROOT = os.path.join(os.path.dirname(__file__), "..")
rows = []
for path in sorted(glob.glob(os.path.join(ROOT, "policies", "*.md"))):
    doc = os.path.basename(path)
    section = ""
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if line.startswith("## "):
            section = line[3:]
        m = re.match(r"^(POL-\d+\.\d+)\s+(.*)$", line)
        if m:
            rows.append((m.group(1), doc, section, m.group(2)))


def q(s):
    return "'" + s.replace("'", "''") + "'"


values = ",\n".join(f"  ({q(c)}, {q(d)}, {q(s)}, {q(t)})" for c, d, s, t in rows)
sql = f"""-- StudyPass | 03 Policy knowledge base (generated by scripts/build_policy_sql.py)
USE SCHEMA STUDYPASS.CORE;

CREATE OR REPLACE TABLE POLICY_CHUNKS (CLAUSE_ID VARCHAR, SOURCE_DOC VARCHAR, SECTION VARCHAR, CLAUSE_TEXT VARCHAR);
INSERT INTO POLICY_CHUNKS VALUES
{values};

-- Unstructured retrieval for free-text compliance questions
CREATE OR REPLACE CORTEX SEARCH SERVICE POLICY_SEARCH
  ON CLAUSE_TEXT
  ATTRIBUTES CLAUSE_ID, SECTION
  WAREHOUSE = STUDYPASS_WH
  TARGET_LAG = '1 day'
  AS SELECT CLAUSE_ID, SOURCE_DOC, SECTION, CLAUSE_TEXT FROM POLICY_CHUNKS;

-- Quick test
SELECT PARSE_JSON(SNOWFLAKE.CORTEX.SEARCH_PREVIEW(
  'STUDYPASS.CORE.POLICY_SEARCH',
  '{{"query": "payments to education agents", "columns": ["CLAUSE_ID","CLAUSE_TEXT"], "limit": 3}}'
))['results'] AS RESULTS;
"""
open(os.path.join(ROOT, "sql", "03_policies.sql"), "w", encoding="utf-8").write(sql)
print(f"{len(rows)} clauses written")
