-- StudyPass | 02 Load synthetic CSVs (run from the repo root so file:// paths resolve)
-- If your client does not support PUT, use:  python scripts/load_to_snowflake.py
USE SCHEMA STUDYPASS.CORE;

PUT file://data/customers.csv   @RAW_STAGE AUTO_COMPRESS = TRUE OVERWRITE = TRUE;
PUT file://data/students.csv    @RAW_STAGE AUTO_COMPRESS = TRUE OVERWRITE = TRUE;
PUT file://data/remittances.csv @RAW_STAGE AUTO_COMPRESS = TRUE OVERWRITE = TRUE;
PUT file://data/card_txns.csv   @RAW_STAGE AUTO_COMPRESS = TRUE OVERWRITE = TRUE;
PUT file://data/documents.csv   @RAW_STAGE AUTO_COMPRESS = TRUE OVERWRITE = TRUE;

COPY INTO CUSTOMERS   FROM @RAW_STAGE/customers.csv.gz   FILE_FORMAT = CSV_FF;
COPY INTO STUDENTS    FROM @RAW_STAGE/students.csv.gz    FILE_FORMAT = CSV_FF;
COPY INTO REMITTANCES FROM @RAW_STAGE/remittances.csv.gz FILE_FORMAT = CSV_FF;
COPY INTO CARD_TXNS   FROM @RAW_STAGE/card_txns.csv.gz   FILE_FORMAT = CSV_FF;
COPY INTO DOCUMENTS   FROM @RAW_STAGE/documents.csv.gz   FILE_FORMAT = CSV_FF;

SELECT 'CUSTOMERS' T, COUNT(*) N FROM CUSTOMERS UNION ALL
SELECT 'STUDENTS', COUNT(*) FROM STUDENTS UNION ALL
SELECT 'REMITTANCES', COUNT(*) FROM REMITTANCES UNION ALL
SELECT 'CARD_TXNS', COUNT(*) FROM CARD_TXNS UNION ALL
SELECT 'DOCUMENTS', COUNT(*) FROM DOCUMENTS;
