-- StudyPass | 04 Risk & fraud signals (governed, explainable views)
-- Every signal row carries: weight, the metric that fired, evidence IDs, and the policy clause applied.
USE SCHEMA STUDYPASS.CORE;

-- Helper: financial year (April-March) start date
CREATE OR REPLACE FUNCTION FY_START(D DATE) RETURNS DATE AS
$$ DATE_FROM_PARTS(IFF(MONTH(D) >= 4, YEAR(D), YEAR(D) - 1), 4, 1) $$;

CREATE OR REPLACE VIEW V_SIG_LRS_BREACH AS
SELECT CUSTOMER_ID, 'LRS_BREACH' AS SIGNAL_CODE, 40 AS WEIGHT, SUM(AMOUNT_USD) AS METRIC_VALUE,
       ARRAY_AGG(REMITTANCE_ID) WITHIN GROUP (ORDER BY TXN_DATE) AS EVIDENCE_IDS, 'POL-2.1' AS POLICY_CLAUSE,
       'FY ' || TO_VARCHAR(FY_START(TXN_DATE), 'YYYY') || ' LRS total USD ' || TO_VARCHAR(ROUND(SUM(AMOUNT_USD)), '999,999,999')
         || ' exceeds USD 250,000 limit' AS DETAIL
FROM REMITTANCES
GROUP BY CUSTOMER_ID, FY_START(TXN_DATE)
HAVING SUM(AMOUNT_USD) > 250000;

CREATE OR REPLACE VIEW V_SIG_STRUCTURING AS
WITH BAND AS (
  SELECT * FROM REMITTANCES
  WHERE PURPOSE_CODE = 'S0305' AND AMOUNT_INR >= 900000 AND AMOUNT_INR < 1000000
), WIN AS (
  SELECT A.CUSTOMER_ID, A.REMITTANCE_ID, COUNT(*) AS N_IN_30D
  FROM BAND A JOIN BAND B
    ON A.CUSTOMER_ID = B.CUSTOMER_ID AND B.TXN_DATE BETWEEN A.TXN_DATE AND DATEADD(DAY, 30, A.TXN_DATE)
  GROUP BY 1, 2
)
SELECT B.CUSTOMER_ID, 'STRUCTURING' AS SIGNAL_CODE, 30 AS WEIGHT, COUNT(*) AS METRIC_VALUE,
       ARRAY_AGG(B.REMITTANCE_ID) WITHIN GROUP (ORDER BY B.TXN_DATE) AS EVIDENCE_IDS, 'POL-5.2' AS POLICY_CLAUSE,
       COUNT(*) || ' remittances of INR 9-10 lakh each (just below the INR 10 lakh threshold), max '
         || MAX(W.N_IN_30D) || ' within 30 days' AS DETAIL
FROM BAND B JOIN (SELECT CUSTOMER_ID, MAX(N_IN_30D) N_IN_30D FROM WIN GROUP BY 1 HAVING MAX(N_IN_30D) >= 3) W
  ON B.CUSTOMER_ID = W.CUSTOMER_ID
GROUP BY B.CUSTOMER_ID;

CREATE OR REPLACE VIEW V_SIG_THIRD_PARTY AS
SELECT CUSTOMER_ID, 'THIRD_PARTY_BENEFICIARY' AS SIGNAL_CODE, 30 AS WEIGHT, SUM(AMOUNT_USD) AS METRIC_VALUE,
       ARRAY_AGG(REMITTANCE_ID) WITHIN GROUP (ORDER BY TXN_DATE) AS EVIDENCE_IDS, 'POL-3.2' AS POLICY_CLAUSE,
       COUNT(*) || ' education remittance(s) totalling USD ' || TO_VARCHAR(ROUND(SUM(AMOUNT_USD)), '999,999,999')
         || ' paid to third party: ' || LISTAGG(DISTINCT BENEFICIARY_NAME, ', ') AS DETAIL
FROM REMITTANCES
WHERE PURPOSE_CODE = 'S0305' AND BENEFICIARY_TYPE = 'THIRD_PARTY'
GROUP BY CUSTOMER_ID;

CREATE OR REPLACE VIEW V_SIG_COUNTRY_MISMATCH AS
SELECT R.CUSTOMER_ID, 'COUNTRY_MISMATCH' AS SIGNAL_CODE, 20 AS WEIGHT, SUM(R.AMOUNT_USD) AS METRIC_VALUE,
       ARRAY_AGG(R.REMITTANCE_ID) WITHIN GROUP (ORDER BY R.TXN_DATE) AS EVIDENCE_IDS, 'POL-3.3' AS POLICY_CLAUSE,
       'Student studies in ' || ANY_VALUE(S.STUDY_COUNTRY) || ' but funds sent to ' || LISTAGG(DISTINCT R.BENEFICIARY_COUNTRY, ', ')
         || IFF(MAX(IFF(H.COUNTRY_CODE IS NOT NULL, 1, 0)) = 1, ' (high-risk jurisdiction)', '') AS DETAIL
FROM REMITTANCES R
JOIN STUDENTS S ON R.STUDENT_ID = S.STUDENT_ID
LEFT JOIN HIGH_RISK_JURISDICTIONS H ON R.BENEFICIARY_COUNTRY = H.COUNTRY_CODE
WHERE R.PURPOSE_CODE = 'S0305' AND R.BENEFICIARY_COUNTRY <> S.STUDY_COUNTRY
GROUP BY R.CUSTOMER_ID;

CREATE OR REPLACE VIEW V_SIG_INACTIVE_ENROLMENT AS
SELECT S.CUSTOMER_ID, 'INACTIVE_ENROLMENT' AS SIGNAL_CODE, 25 AS WEIGHT, SUM(R.AMOUNT_USD) AS METRIC_VALUE,
       ARRAY_CAT(ARRAY_AGG(DISTINCT R.REMITTANCE_ID), ARRAY_AGG(DISTINCT D.DOC_ID)) AS EVIDENCE_IDS, 'POL-4.2' AS POLICY_CLAUSE,
       'Enrolment status ' || ANY_VALUE(S.ENROLMENT_STATUS) || ' at ' || ANY_VALUE(S.UNIVERSITY_NAME)
         || '; offer letter not verified; ' || COUNT(DISTINCT R.REMITTANCE_ID) || ' remittance(s) still sent' AS DETAIL
FROM STUDENTS S
JOIN REMITTANCES R ON R.STUDENT_ID = S.STUDENT_ID AND R.PURPOSE_CODE = 'S0305'
LEFT JOIN DOCUMENTS D ON D.STUDENT_ID = S.STUDENT_ID AND D.VERIFIED = FALSE
WHERE S.ENROLMENT_STATUS <> 'ACTIVE'
GROUP BY S.CUSTOMER_ID;

CREATE OR REPLACE VIEW V_SIG_FEE_INFLATION AS
SELECT R.CUSTOMER_ID, 'FEE_INFLATION' AS SIGNAL_CODE, 15 AS WEIGHT,
       ROUND(SUM(R.AMOUNT_USD) / ANY_VALUE(S.DECLARED_ANNUAL_FEE_USD), 2) AS METRIC_VALUE,
       ARRAY_AGG(R.REMITTANCE_ID) WITHIN GROUP (ORDER BY R.TXN_DATE) AS EVIDENCE_IDS, 'POL-4.3' AS POLICY_CLAUSE,
       'Tuition paid USD ' || TO_VARCHAR(ROUND(SUM(R.AMOUNT_USD)), '999,999,999') || ' = '
         || ROUND(100 * SUM(R.AMOUNT_USD) / ANY_VALUE(S.DECLARED_ANNUAL_FEE_USD)) || '% of declared fee (limit 120%)' AS DETAIL
FROM REMITTANCES R JOIN STUDENTS S ON R.STUDENT_ID = S.STUDENT_ID
WHERE R.PURPOSE_CODE = 'S0305' AND R.BENEFICIARY_TYPE = 'UNIVERSITY'
GROUP BY R.CUSTOMER_ID, FY_START(R.TXN_DATE)
HAVING SUM(R.AMOUNT_USD) > 1.2 * ANY_VALUE(S.DECLARED_ANNUAL_FEE_USD);

CREATE OR REPLACE VIEW V_SIG_CARD_RISKY_MCC AS
SELECT C.CUSTOMER_ID, 'CARD_RISKY_MCC' AS SIGNAL_CODE, 20 AS WEIGHT, SUM(C.AMOUNT_USD) AS METRIC_VALUE,
       ARRAY_AGG(C.TXN_ID) WITHIN GROUP (ORDER BY C.TXN_TS) AS EVIDENCE_IDS, 'POL-6.2' AS POLICY_CLAUSE,
       COUNT(*) || ' forex-card txn(s) at ' || LISTAGG(DISTINCT C.MCC_DESC, ', ') || ' totalling USD '
         || TO_VARCHAR(ROUND(SUM(C.AMOUNT_USD)), '999,999,999')
         || IFF(MAX(IFF(H.COUNTRY_CODE IS NOT NULL, 1, 0)) = 1, ', incl. high-risk jurisdiction', '') AS DETAIL
FROM CARD_TXNS C LEFT JOIN HIGH_RISK_JURISDICTIONS H ON C.MERCHANT_COUNTRY = H.COUNTRY_CODE
WHERE C.MCC IN ('7995', '6051', '4829')
GROUP BY C.CUSTOMER_ID
HAVING COUNT(*) >= 2 OR MAX(IFF(H.COUNTRY_CODE IS NOT NULL, 1, 0)) = 1;

-- One governed signal feed
CREATE OR REPLACE VIEW V_RISK_SIGNALS AS
          SELECT * FROM V_SIG_LRS_BREACH
UNION ALL SELECT * FROM V_SIG_STRUCTURING
UNION ALL SELECT * FROM V_SIG_THIRD_PARTY
UNION ALL SELECT * FROM V_SIG_COUNTRY_MISMATCH
UNION ALL SELECT * FROM V_SIG_INACTIVE_ENROLMENT
UNION ALL SELECT * FROM V_SIG_FEE_INFLATION
UNION ALL SELECT * FROM V_SIG_CARD_RISKY_MCC;

-- Customer-level risk score (POL-7)
CREATE OR REPLACE VIEW V_CUSTOMER_RISK AS
SELECT S.CUSTOMER_ID, C.CUSTOMER_NAME, C.CITY, C.KYC_RISK_RATING,
       SUM(S.WEIGHT) AS RISK_SCORE,
       CASE WHEN SUM(S.WEIGHT) >= 40 THEN 'HIGH' WHEN SUM(S.WEIGHT) >= 20 THEN 'MEDIUM' ELSE 'LOW' END AS RISK_BAND,
       ARRAY_AGG(S.SIGNAL_CODE) WITHIN GROUP (ORDER BY S.WEIGHT DESC) AS SIGNALS,
       ARRAY_AGG(DISTINCT S.POLICY_CLAUSE) AS POLICY_CLAUSES
FROM V_RISK_SIGNALS S JOIN CUSTOMERS C ON S.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY S.CUSTOMER_ID, C.CUSTOMER_NAME, C.CITY, C.KYC_RISK_RATING;

-- Portfolio summary for "what's happening?" questions
CREATE OR REPLACE VIEW V_SIGNAL_SUMMARY AS
SELECT SIGNAL_CODE, POLICY_CLAUSE, COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMERS_FLAGGED, ROUND(SUM(METRIC_VALUE), 2) AS TOTAL_METRIC
FROM V_RISK_SIGNALS GROUP BY 1, 2 ORDER BY CUSTOMERS_FLAGGED DESC;

SELECT * FROM V_SIGNAL_SUMMARY;
SELECT * FROM V_CUSTOMER_RISK ORDER BY RISK_SCORE DESC LIMIT 10;
