-- StudyPass | 06 Governance: least-privilege role, PII masking, audit
-- Needs a role with CREATE ROLE / MANAGE GRANTS (e.g. ACCOUNTADMIN on a trial account).
USE SCHEMA STUDYPASS.CORE;

CREATE ROLE IF NOT EXISTS COMPLIANCE_ANALYST;
SET CURRENT_USER_NAME = CURRENT_USER();
GRANT ROLE COMPLIANCE_ANALYST TO USER IDENTIFIER($CURRENT_USER_NAME);

-- Mask PAN and account numbers for everyone except the data owner role
CREATE OR REPLACE MASKING POLICY MASK_PII AS (VAL STRING) RETURNS STRING ->
  CASE WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') OR IS_ROLE_IN_SESSION('SYSADMIN') THEN VAL
       ELSE REPEAT('*', GREATEST(LENGTH(VAL) - 4, 0)) || RIGHT(VAL, 4) END;
ALTER TABLE CUSTOMERS MODIFY COLUMN PAN        SET MASKING POLICY MASK_PII;
ALTER TABLE CUSTOMERS MODIFY COLUMN ACCOUNT_NO SET MASKING POLICY MASK_PII;

-- Analysts read governed views and run the procedures; they cannot change raw data
GRANT USAGE ON WAREHOUSE STUDYPASS_WH TO ROLE COMPLIANCE_ANALYST;
GRANT USAGE ON DATABASE STUDYPASS TO ROLE COMPLIANCE_ANALYST;
GRANT USAGE ON SCHEMA STUDYPASS.CORE TO ROLE COMPLIANCE_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA STUDYPASS.CORE TO ROLE COMPLIANCE_ANALYST;
GRANT SELECT ON TABLE CUSTOMERS, STUDENTS, REMITTANCES, CARD_TXNS, DOCUMENTS, POLICY_CHUNKS TO ROLE COMPLIANCE_ANALYST;
GRANT SELECT, INSERT, UPDATE ON TABLE CASE_FINDINGS TO ROLE COMPLIANCE_ANALYST;
GRANT INSERT, SELECT ON TABLE AUDIT_LOG TO ROLE COMPLIANCE_ANALYST;
GRANT USAGE ON CORTEX SEARCH SERVICE POLICY_SEARCH TO ROLE COMPLIANCE_ANALYST;
GRANT USAGE ON PROCEDURE SP_DRAFT_FINDING(VARCHAR, VARCHAR) TO ROLE COMPLIANCE_ANALYST;
GRANT USAGE ON PROCEDURE SP_REVIEW_FINDING(VARCHAR, VARCHAR) TO ROLE COMPLIANCE_ANALYST;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE COMPLIANCE_ANALYST;
