-- StudyPass | 01 Setup: warehouse, database, raw tables, stage
-- Run as a role that can create databases (e.g. SYSADMIN or ACCOUNTADMIN on a trial account).

CREATE WAREHOUSE IF NOT EXISTS STUDYPASS_WH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE DATABASE IF NOT EXISTS STUDYPASS;
CREATE SCHEMA IF NOT EXISTS STUDYPASS.CORE;
USE WAREHOUSE STUDYPASS_WH;
USE SCHEMA STUDYPASS.CORE;

CREATE OR REPLACE FILE FORMAT CSV_FF TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = ('');
CREATE STAGE IF NOT EXISTS RAW_STAGE FILE_FORMAT = CSV_FF;

CREATE OR REPLACE TABLE CUSTOMERS (
  CUSTOMER_ID VARCHAR, CUSTOMER_NAME VARCHAR, PAN VARCHAR, CITY VARCHAR, SEGMENT VARCHAR,
  KYC_RISK_RATING VARCHAR, ACCOUNT_NO VARCHAR, ONBOARDED_ON DATE);

CREATE OR REPLACE TABLE STUDENTS (
  STUDENT_ID VARCHAR, CUSTOMER_ID VARCHAR, STUDENT_NAME VARCHAR, UNIVERSITY_ID VARCHAR, UNIVERSITY_NAME VARCHAR,
  STUDY_COUNTRY VARCHAR, PROGRAM VARCHAR, DECLARED_ANNUAL_FEE_USD NUMBER(12,2), INTAKE_DATE DATE,
  ENROLMENT_STATUS VARCHAR, FOREX_CARD_ID VARCHAR);

CREATE OR REPLACE TABLE REMITTANCES (
  REMITTANCE_ID VARCHAR, CUSTOMER_ID VARCHAR, STUDENT_ID VARCHAR, TXN_DATE DATE, AMOUNT_USD NUMBER(14,2),
  AMOUNT_INR NUMBER(16,0), PURPOSE_CODE VARCHAR, BENEFICIARY_TYPE VARCHAR, BENEFICIARY_NAME VARCHAR,
  BENEFICIARY_COUNTRY VARCHAR, CHANNEL VARCHAR, TCS_COLLECTED_INR NUMBER(14,0));

CREATE OR REPLACE TABLE CARD_TXNS (
  TXN_ID VARCHAR, FOREX_CARD_ID VARCHAR, CUSTOMER_ID VARCHAR, TXN_TS TIMESTAMP_NTZ, MCC VARCHAR,
  MCC_DESC VARCHAR, MERCHANT_COUNTRY VARCHAR, AMOUNT_USD NUMBER(12,2));

CREATE OR REPLACE TABLE DOCUMENTS (
  DOC_ID VARCHAR, CUSTOMER_ID VARCHAR, STUDENT_ID VARCHAR, DOC_TYPE VARCHAR, VERIFIED BOOLEAN,
  AMOUNT_USD NUMBER(12,2), UPLOADED_ON DATE);

CREATE OR REPLACE TABLE HIGH_RISK_JURISDICTIONS (COUNTRY_CODE VARCHAR, REASON VARCHAR);
INSERT INTO HIGH_RISK_JURISDICTIONS VALUES
  ('AE','Prototype high-risk list'), ('HK','Prototype high-risk list'),
  ('CY','Prototype high-risk list'), ('PA','Prototype high-risk list');

-- Findings and audit trail (written by the str-report skill / SP_DRAFT_FINDING)
CREATE TABLE IF NOT EXISTS CASE_FINDINGS (
  FINDING_ID VARCHAR DEFAULT UUID_STRING(), CUSTOMER_ID VARCHAR, RISK_SCORE NUMBER, RISK_BAND VARCHAR,
  SIGNALS ARRAY, EVIDENCE_IDS ARRAY, POLICY_CLAUSES ARRAY, NARRATIVE VARCHAR,
  STATUS VARCHAR DEFAULT 'DRAFT_PENDING_REVIEW', CREATED_BY VARCHAR DEFAULT CURRENT_USER(),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), REVIEWED_BY VARCHAR, REVIEWED_AT TIMESTAMP_NTZ);

CREATE TABLE IF NOT EXISTS AUDIT_LOG (
  EVENT_ID VARCHAR DEFAULT UUID_STRING(), EVENT_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  ACTOR VARCHAR DEFAULT CURRENT_USER(), ROLE_NAME VARCHAR DEFAULT CURRENT_ROLE(),
  ACTION VARCHAR, CUSTOMER_ID VARCHAR, DETAILS VARIANT);
