-- StudyPass | 03 Policy knowledge base (generated by scripts/build_policy_sql.py)
USE SCHEMA STUDYPASS.CORE;

CREATE OR REPLACE TABLE POLICY_CHUNKS (CLAUSE_ID VARCHAR, SOURCE_DOC VARCHAR, SECTION VARCHAR, CLAUSE_TEXT VARCHAR);
INSERT INTO POLICY_CHUNKS VALUES
  ('POL-1.1', 'education_remittance_policy.md', 'POL-1 Scope', 'This policy covers outward remittances under purpose code S0305 (education abroad) and transactions on student forex cards issued to, or funded by, resident individual customers.'),
  ('POL-1.2', 'education_remittance_policy.md', 'POL-1 Scope', 'The remitter is the resident customer (usually a parent). The beneficiary is the foreign university or the student''s own verified account abroad.'),
  ('POL-2.1', 'education_remittance_policy.md', 'POL-2 LRS limit', 'The aggregate of all remittances by a resident individual under the Liberalised Remittance Scheme must not exceed USD 250,000 in a financial year (April to March), across all purposes and all banks.'),
  ('POL-2.2', 'education_remittance_policy.md', 'POL-2 LRS limit', 'A remittance that would take the customer''s financial-year total above USD 250,000 must be stopped and referred to Compliance. A breach that has already happened is a reportable finding.'),
  ('POL-3.1', 'education_remittance_policy.md', 'POL-3 Beneficiary and purpose consistency', 'Education remittances must be paid to the university named on the offer letter or fee invoice, or to an account in the student''s own name in the country of study.'),
  ('POL-3.2', 'education_remittance_policy.md', 'POL-3 Beneficiary and purpose consistency', 'Payments under S0305 to a third party (agents, consultants, trading entities) are not permitted unless supported by a university-issued authorisation. Without it, raise a finding for possible purpose misuse.'),
  ('POL-3.3', 'education_remittance_policy.md', 'POL-3 Beneficiary and purpose consistency', 'The beneficiary country must match the student''s country of study. A mismatch, especially to a jurisdiction on the bank''s high-risk list (AE, HK, CY, PA in this prototype), requires enhanced due diligence.'),
  ('POL-4.1', 'education_remittance_policy.md', 'POL-4 Supporting documents', 'Each S0305 remittance needs a verified offer letter or admission proof, a fee invoice, and a signed Form A2.'),
  ('POL-4.2', 'education_remittance_policy.md', 'POL-4 Supporting documents', 'If the student''s enrolment is withdrawn or cannot be verified, further S0305 remittances must be paused and existing ones reviewed.'),
  ('POL-4.3', 'education_remittance_policy.md', 'POL-4 Supporting documents', 'Tuition remitted in a financial year should not exceed 120% of the declared annual fee on the invoice. Amounts above this need a fresh invoice or an explanation recorded on file.'),
  ('POL-5.1', 'education_remittance_policy.md', 'POL-5 Structuring', 'Structuring means splitting remittances to stay below a threshold (for example the INR 10 lakh TCS threshold or internal review limits).'),
  ('POL-5.2', 'education_remittance_policy.md', 'POL-5 Structuring', 'Three or more S0305 remittances, each between 90% and 100% of INR 10 lakh, within 30 days, must be treated as a structuring alert.'),
  ('POL-6.1', 'education_remittance_policy.md', 'POL-6 Forex card monitoring', 'Student forex cards are for the student''s living and study costs in the country of study.'),
  ('POL-6.2', 'education_remittance_policy.md', 'POL-6 Forex card monitoring', 'Card spend at gambling (MCC 7995), crypto or quasi-cash (MCC 6051), or money-transfer merchants (MCC 4829) is a red flag. Two or more such transactions, or any such transaction in a high-risk jurisdiction, must raise an alert.'),
  ('POL-7.1', 'education_remittance_policy.md', 'POL-7 Risk scoring and escalation', 'Each signal carries a weight: LRS breach 40, third-party beneficiary 30, structuring 30, inactive enrolment 25, country mismatch 20, risky card MCC 20, fee inflation 15.'),
  ('POL-7.2', 'education_remittance_policy.md', 'POL-7 Risk scoring and escalation', 'A customer with a total score of 40 or more is HIGH risk and must be reviewed by a Compliance Analyst within 2 working days. 20 to 39 is MEDIUM risk.'),
  ('POL-7.3', 'education_remittance_policy.md', 'POL-7 Risk scoring and escalation', 'Every finding must cite the transaction IDs and document IDs used as evidence and the policy clauses applied.'),
  ('POL-8.1', 'education_remittance_policy.md', 'POL-8 Suspicious Transaction Reports', 'If the reviewer concludes that a transaction is suspicious, a Suspicious Transaction Report (STR) must be filed with FIU-IND within 7 working days of reaching that conclusion.'),
  ('POL-8.2', 'education_remittance_policy.md', 'POL-8 Suspicious Transaction Reports', 'The STR narrative must state who, what, when, how much, why it is suspicious, and the evidence relied upon. It must not be shared with the customer (no tipping-off).'),
  ('POL-8.3', 'education_remittance_policy.md', 'POL-8 Suspicious Transaction Reports', 'Every AI-drafted narrative is a draft only. A named Compliance Analyst must review and approve it before filing. The approval is logged.');

-- Unstructured retrieval for free-text compliance questions
CREATE OR REPLACE CORTEX SEARCH SERVICE POLICY_SEARCH
  ON CLAUSE_TEXT
  ATTRIBUTES CLAUSE_ID, SECTION
  WAREHOUSE = STUDYPASS_WH
  TARGET_LAG = '1 day'
  AS SELECT CLAUSE_ID, SOURCE_DOC, SECTION, CLAUSE_TEXT FROM POLICY_CHUNKS;

-- Quick test
SELECT PARSE_JSON(SNOWFLAKE.CORTEX.SEARCH_PREVIEW(
  'STUDYPASS.CORE.POLICY_SEARCH',
  '{"query": "payments to education agents", "columns": ["CLAUSE_ID","CLAUSE_TEXT"], "limit": 3}'
))['results'] AS RESULTS;
